# Generated by Django 4.0.5 on 2022-06-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(max_length=200)),
                ('package_name', models.CharField(max_length=200)),
                ('package_version_code', models.IntegerField()),
                ('icon', models.CharField(max_length=200)),
            ],
        ),
    ]
