# Generated by Django 4.0.5 on 2022-06-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='package_version_code',
            field=models.CharField(max_length=200),
        ),
    ]
